# Array Stacking

In [6]:
import numpy as np
a1 = np.arange(0,25).reshape(5,5)
a2 = np.linspace(3,4, 10).reshape(2,5)
a3 = np.linspace(2,3, 25).reshape(5,5)
a5 = np.linspace(3,4, 15).reshape(5,3)
a1, a2, a3, a5

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 array([[3.        , 3.11111111, 3.22222222, 3.33333333, 3.44444444],
        [3.55555556, 3.66666667, 3.77777778, 3.88888889, 4.        ]]),
 array([[2.        , 2.04166667, 2.08333333, 2.125     , 2.16666667],
        [2.20833333, 2.25      , 2.29166667, 2.33333333, 2.375     ],
        [2.41666667, 2.45833333, 2.5       , 2.54166667, 2.58333333],
        [2.625     , 2.66666667, 2.70833333, 2.75      , 2.79166667],
        [2.83333333, 2.875     , 2.91666667, 2.95833333, 3.        ]]),
 array([[3.        , 3.07142857, 3.14285714],
        [3.21428571, 3.28571429, 3.35714286],
        [3.42857143, 3.5       , 3.57142857],
        [3.64285714, 3.71428571, 3.78571429],
        [3.85714286, 3.92857143, 4.        ]]))

### Vartical Stack

In [7]:
aV = np.vstack((a1, a2, a3))
aV

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ],
       [10.        , 11.        , 12.        , 13.        , 14.        ],
       [15.        , 16.        , 17.        , 18.        , 19.        ],
       [20.        , 21.        , 22.        , 23.        , 24.        ],
       [ 3.        ,  3.11111111,  3.22222222,  3.33333333,  3.44444444],
       [ 3.55555556,  3.66666667,  3.77777778,  3.88888889,  4.        ],
       [ 2.        ,  2.04166667,  2.08333333,  2.125     ,  2.16666667],
       [ 2.20833333,  2.25      ,  2.29166667,  2.33333333,  2.375     ],
       [ 2.41666667,  2.45833333,  2.5       ,  2.54166667,  2.58333333],
       [ 2.625     ,  2.66666667,  2.70833333,  2.75      ,  2.79166667],
       [ 2.83333333,  2.875     ,  2.91666667,  2.95833333,  3.        ]])

In [8]:
aV = np.vstack((a1, a2, a3, a5)) # ERROR (Vertically axises must match)
aV

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 3 has size 3

In [9]:
b1, b2, b3 = np.vsplit(aV,3) # All elements will get equally devided
b1, b2, b3

(array([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]),
 array([[20.        , 21.        , 22.        , 23.        , 24.        ],
        [ 3.        ,  3.11111111,  3.22222222,  3.33333333,  3.44444444],
        [ 3.55555556,  3.66666667,  3.77777778,  3.88888889,  4.        ],
        [ 2.        ,  2.04166667,  2.08333333,  2.125     ,  2.16666667]]),
 array([[2.20833333, 2.25      , 2.29166667, 2.33333333, 2.375     ],
        [2.41666667, 2.45833333, 2.5       , 2.54166667, 2.58333333],
        [2.625     , 2.66666667, 2.70833333, 2.75      , 2.79166667],
        [2.83333333, 2.875     , 2.91666667, 2.95833333, 3.        ]]))

### Horizontal Stack

same as vstack

In [10]:
aH = np.hstack((a1, a3, a5)) # (Horizontally axises must match)
aH

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
         2.        ,  2.04166667,  2.08333333,  2.125     ,  2.16666667,
         3.        ,  3.07142857,  3.14285714],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
         2.20833333,  2.25      ,  2.29166667,  2.33333333,  2.375     ,
         3.21428571,  3.28571429,  3.35714286],
       [10.        , 11.        , 12.        , 13.        , 14.        ,
         2.41666667,  2.45833333,  2.5       ,  2.54166667,  2.58333333,
         3.42857143,  3.5       ,  3.57142857],
       [15.        , 16.        , 17.        , 18.        , 19.        ,
         2.625     ,  2.66666667,  2.70833333,  2.75      ,  2.79166667,
         3.64285714,  3.71428571,  3.78571429],
       [20.        , 21.        , 22.        , 23.        , 24.        ,
         2.83333333,  2.875     ,  2.91666667,  2.95833333,  3.        ,
         3.85714286,  3.92857143,  4.        ]])

### Concatenate

In [11]:
cV = np.concatenate((a1, a2, a3), axis=0) # Same as vstack()
cH = np.concatenate((a1, a5, a3), axis = 1) # Same as hstack()
cV.shape, cH.shape, cV, cH

((12, 5),
 (5, 13),
 array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
        [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ],
        [10.        , 11.        , 12.        , 13.        , 14.        ],
        [15.        , 16.        , 17.        , 18.        , 19.        ],
        [20.        , 21.        , 22.        , 23.        , 24.        ],
        [ 3.        ,  3.11111111,  3.22222222,  3.33333333,  3.44444444],
        [ 3.55555556,  3.66666667,  3.77777778,  3.88888889,  4.        ],
        [ 2.        ,  2.04166667,  2.08333333,  2.125     ,  2.16666667],
        [ 2.20833333,  2.25      ,  2.29166667,  2.33333333,  2.375     ],
        [ 2.41666667,  2.45833333,  2.5       ,  2.54166667,  2.58333333],
        [ 2.625     ,  2.66666667,  2.70833333,  2.75      ,  2.79166667],
        [ 2.83333333,  2.875     ,  2.91666667,  2.95833333,  3.        ]]),
 array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
    

### Stack

stack() function stacks arrays in a new sxis (all array have to have the same shape)

In [12]:
dS = np.stack((a1, a3))
dS.shape, dS

((2, 5, 5),
 array([[[ 0.        ,  1.        ,  2.        ,  3.        ,
           4.        ],
         [ 5.        ,  6.        ,  7.        ,  8.        ,
           9.        ],
         [10.        , 11.        , 12.        , 13.        ,
          14.        ],
         [15.        , 16.        , 17.        , 18.        ,
          19.        ],
         [20.        , 21.        , 22.        , 23.        ,
          24.        ]],
 
        [[ 2.        ,  2.04166667,  2.08333333,  2.125     ,
           2.16666667],
         [ 2.20833333,  2.25      ,  2.29166667,  2.33333333,
           2.375     ],
         [ 2.41666667,  2.45833333,  2.5       ,  2.54166667,
           2.58333333],
         [ 2.625     ,  2.66666667,  2.70833333,  2.75      ,
           2.79166667],
         [ 2.83333333,  2.875     ,  2.91666667,  2.95833333,
           3.        ]]]))

### Transposing

In [13]:
print(dS.shape)
dS = dS.transpose(2,0,1)
print(dS.shape)

(2, 5, 5)
(5, 2, 5)


In [14]:
dS = dS.transpose(0, 2, 1)
print(dS.shape)
dS = dS.transpose()
print(dS.shape)

(5, 5, 2)
(2, 5, 5)


In [15]:
print(dS.shape)
dS = dS.swapaxes(0, 1)
print(dS.shape)

(2, 5, 5)
(5, 2, 5)
