In [7]:
import numpy as np
import numpy.linalg as linalg

# Linear Algebra

In [2]:
x = np.arange(45).reshape(5, 9)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [4]:
x = x.T # same as transpose, but only works on upto 2D arrays
x

array([[ 0,  9, 18, 27, 36],
       [ 1, 10, 19, 28, 37],
       [ 2, 11, 20, 29, 38],
       [ 3, 12, 21, 30, 39],
       [ 4, 13, 22, 31, 40],
       [ 5, 14, 23, 32, 41],
       [ 6, 15, 24, 33, 42],
       [ 7, 16, 25, 34, 43],
       [ 8, 17, 26, 35, 44]])

### Matrix Multiplication

In [9]:
y = np.arange(10).reshape(5,2)
y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
z = x.dot(y)

### Determinant

In [31]:
z = np.linspace(1, 278, 625).reshape(25, 25)
print(z)
x = linalg.det(z)
x

[[  1.           1.44391026   1.88782051   2.33173077   2.77564103
    3.21955128   3.66346154   4.10737179   4.55128205   4.99519231
    5.43910256   5.88301282   6.32692308   6.77083333   7.21474359
    7.65865385   8.1025641    8.54647436   8.99038462   9.43429487
    9.87820513  10.32211538  10.76602564  11.2099359   11.65384615]
 [ 12.09775641  12.54166667  12.98557692  13.42948718  13.87339744
   14.31730769  14.76121795  15.20512821  15.64903846  16.09294872
   16.53685897  16.98076923  17.42467949  17.86858974  18.3125
   18.75641026  19.20032051  19.64423077  20.08814103  20.53205128
   20.97596154  21.41987179  21.86378205  22.30769231  22.75160256]
 [ 23.19551282  23.63942308  24.08333333  24.52724359  24.97115385
   25.4150641   25.85897436  26.30288462  26.74679487  27.19070513
   27.63461538  28.07852564  28.5224359   28.96634615  29.41025641
   29.85416667  30.29807692  30.74198718  31.18589744  31.62980769
   32.07371795  32.51762821  32.96153846  33.40544872  33.849358

np.float64(-5.37902682796e-313)