# Save & Load

In [27]:
import numpy as np
a = np.random.randn(4840, 2160)
b = np.random.rand(4840, 2160)
a, b

(array([[ 0.2339907 , -0.20074114,  1.5164425 , ..., -1.58367993,
          1.96717018,  1.22293421],
        [-0.38971029, -0.86692403,  0.4196243 , ...,  1.36710983,
          1.74278971, -0.08905368],
        [-0.37921452, -0.67159361,  1.39216174, ...,  1.11368736,
          0.41278471, -1.64804629],
        ...,
        [ 0.57830021,  1.18061605,  0.73579455, ...,  0.3956883 ,
          1.23248743, -0.91074881],
        [ 0.35993681, -1.15766264,  3.0168695 , ...,  0.85251686,
         -0.29708019, -0.46676933],
        [-0.02028095,  1.32787299, -1.21761409, ...,  0.41446586,
          0.95335511, -1.40597711]], shape=(4840, 2160)),
 array([[0.54751745, 0.33134406, 0.68844305, ..., 0.52615288, 0.51751853,
         0.30623842],
        [0.21748896, 0.49535974, 0.32236025, ..., 0.11753144, 0.66945265,
         0.53548761],
        [0.24731816, 0.89194366, 0.22878578, ..., 0.26132621, 0.66841472,
         0.94919793],
        ...,
        [0.48004959, 0.17602435, 0.9811887 , ..., 0.

In [29]:
np.save("array_a", a)
x = np.load("array_a.npy")
x

array([[ 0.2339907 , -0.20074114,  1.5164425 , ..., -1.58367993,
         1.96717018,  1.22293421],
       [-0.38971029, -0.86692403,  0.4196243 , ...,  1.36710983,
         1.74278971, -0.08905368],
       [-0.37921452, -0.67159361,  1.39216174, ...,  1.11368736,
         0.41278471, -1.64804629],
       ...,
       [ 0.57830021,  1.18061605,  0.73579455, ...,  0.3956883 ,
         1.23248743, -0.91074881],
       [ 0.35993681, -1.15766264,  3.0168695 , ...,  0.85251686,
        -0.29708019, -0.46676933],
       [-0.02028095,  1.32787299, -1.21761409, ...,  0.41446586,
         0.95335511, -1.40597711]], shape=(4840, 2160))

In [30]:
np.savetxt("arrayB.csv", b)
x = np.loadtxt("arrayB.csv") # This method is slower than binary format.
x

array([[0.54751745, 0.33134406, 0.68844305, ..., 0.52615288, 0.51751853,
        0.30623842],
       [0.21748896, 0.49535974, 0.32236025, ..., 0.11753144, 0.66945265,
        0.53548761],
       [0.24731816, 0.89194366, 0.22878578, ..., 0.26132621, 0.66841472,
        0.94919793],
       ...,
       [0.48004959, 0.17602435, 0.9811887 , ..., 0.57082395, 0.77137489,
        0.1340658 ],
       [0.79540661, 0.93122518, 0.21634467, ..., 0.4199247 , 0.91381555,
        0.94707415],
       [0.55912861, 0.90737873, 0.36514623, ..., 0.01044876, 0.79814995,
        0.26366059]], shape=(4840, 2160))

In [31]:
np.savez("array_a_b.npz", arrayA = a, arrayB = b)


In [32]:
x = np.load("array_a_b.npz")
x["arrayA"], x["arrayB"]

(array([[ 0.2339907 , -0.20074114,  1.5164425 , ..., -1.58367993,
          1.96717018,  1.22293421],
        [-0.38971029, -0.86692403,  0.4196243 , ...,  1.36710983,
          1.74278971, -0.08905368],
        [-0.37921452, -0.67159361,  1.39216174, ...,  1.11368736,
          0.41278471, -1.64804629],
        ...,
        [ 0.57830021,  1.18061605,  0.73579455, ...,  0.3956883 ,
          1.23248743, -0.91074881],
        [ 0.35993681, -1.15766264,  3.0168695 , ...,  0.85251686,
         -0.29708019, -0.46676933],
        [-0.02028095,  1.32787299, -1.21761409, ...,  0.41446586,
          0.95335511, -1.40597711]], shape=(4840, 2160)),
 array([[0.54751745, 0.33134406, 0.68844305, ..., 0.52615288, 0.51751853,
         0.30623842],
        [0.21748896, 0.49535974, 0.32236025, ..., 0.11753144, 0.66945265,
         0.53548761],
        [0.24731816, 0.89194366, 0.22878578, ..., 0.26132621, 0.66841472,
         0.94919793],
        ...,
        [0.48004959, 0.17602435, 0.9811887 , ..., 0.